In [1]:
import prototypes.BoseHubbardModel as bh
import numpy as np

## Testing basic functionalities of the code.

In [2]:
bh.AdjacencyMatrix(6).withPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [3]:
bh.AdjacencyMatrix(6).withoutPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

In [17]:
basis = bh.ONVBasis(4,4)

In [18]:
basis.ONVs

array([[4, 0, 0, 0],
       [3, 1, 0, 0],
       [3, 0, 1, 0],
       [3, 0, 0, 1],
       [2, 2, 0, 0],
       [2, 1, 1, 0],
       [2, 1, 0, 1],
       [2, 0, 2, 0],
       [2, 0, 1, 1],
       [2, 0, 0, 2],
       [1, 3, 0, 0],
       [1, 2, 1, 0],
       [1, 2, 0, 1],
       [1, 1, 2, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 2],
       [1, 0, 3, 0],
       [1, 0, 2, 1],
       [1, 0, 1, 2],
       [1, 0, 0, 3],
       [0, 4, 0, 0],
       [0, 3, 1, 0],
       [0, 3, 0, 1],
       [0, 2, 2, 0],
       [0, 2, 1, 1],
       [0, 2, 0, 2],
       [0, 1, 3, 0],
       [0, 1, 2, 1],
       [0, 1, 1, 2],
       [0, 1, 0, 3],
       [0, 0, 4, 0],
       [0, 0, 3, 1],
       [0, 0, 2, 2],
       [0, 0, 1, 3],
       [0, 0, 0, 4]])

In [29]:
# 3 sites, 3 bosons
# t=0.1, U=2
# w_ii = 0
# Periodic boundary conditions

H = bh.BoseHubbardHamiltonian(4,4, 0.1, 2, [0]*4, True)

In [30]:
print(basis.evaluateHamiltonian(H))

  (0, 0)	12.0
  (0, 1)	0.2
  (0, 3)	0.2
  (1, 0)	0.2
  (1, 1)	6.0
  (1, 2)	0.1
  (1, 4)	0.2449489742783178
  (1, 6)	0.17320508075688773
  (2, 1)	0.1
  (2, 2)	6.0
  (2, 3)	0.1
  (2, 5)	0.17320508075688773
  (2, 8)	0.17320508075688773
  (3, 0)	0.2
  (3, 2)	0.1
  (3, 3)	6.0
  (3, 6)	0.17320508075688773
  (3, 9)	0.2449489742783178
  (4, 1)	0.2449489742783178
  (4, 4)	4.0
  (4, 5)	0.14142135623730953
  (4, 10)	0.2449489742783178
  (4, 12)	0.14142135623730953
  (5, 2)	0.17320508075688773
  (5, 4)	0.14142135623730953
  :	:
  (29, 19)	0.1
  (29, 28)	0.17320508075688773
  (29, 29)	6.0
  (29, 33)	0.1
  (30, 26)	0.2
  (30, 30)	12.0
  (30, 31)	0.2
  (31, 16)	0.1
  (31, 27)	0.17320508075688773
  (31, 30)	0.2
  (31, 31)	6.0
  (31, 32)	0.2449489742783178
  (32, 17)	0.14142135623730953
  (32, 28)	0.14142135623730953
  (32, 31)	0.2449489742783178
  (32, 32)	4.0
  (32, 33)	0.2449489742783178
  (33, 18)	0.17320508075688773
  (33, 29)	0.1
  (33, 32)	0.2449489742783178
  (33, 33)	6.0
  (33, 34)	0.2
  (34, 

## Solving the problem.

In [31]:
H_eval = basis.evaluateHamiltonian(H)
GSParameters = bh.BoseHubbardSolver(H_eval).groundState()

In [32]:
GSParameters.energy.real

-0.08183183291653322

In [10]:
GSParameters.C.real

array([ 1.47748986e-11, -9.08388026e-10,  1.07171250e-08, -4.29365405e-08,
        1.07171251e-08, -9.08387890e-10,  1.87706303e-08, -3.95358506e-07,
        1.92689214e-06, -5.49345386e-07,  5.03807711e-08,  1.02082227e-06,
       -1.45939129e-05,  5.40518626e-06, -5.49345387e-07,  2.00074828e-06,
       -1.45939129e-05,  1.92689214e-06,  1.02082227e-06, -3.95358506e-07,
        1.87706302e-08, -9.22171833e-08,  3.18885471e-06, -2.17463161e-05,
        8.37816412e-06, -8.84468485e-07, -2.16858951e-05,  3.14989927e-04,
       -1.56203183e-04,  1.77381314e-05, -6.03060964e-05,  5.63585990e-04,
       -7.81967530e-05, -3.97842613e-05,  1.77381314e-05, -8.84468485e-07,
        2.40838822e-06, -6.25762107e-05,  2.81719855e-04, -3.97842613e-05,
        2.79125373e-04, -3.92195746e-03,  5.63585990e-04,  2.81719855e-04,
       -1.56203183e-04,  8.37816412e-06, -1.59559806e-05,  2.79125373e-04,
       -6.03060964e-05, -6.25762107e-05,  3.14989927e-04, -2.17463161e-05,
        2.40838822e-06, -

In [11]:
np.set_printoptions(3, suppress=True)
GSParameters.singleParticleDensityMatrix().real

array([[ 0., -0.,  0., ...,  0., -0.,  0.],
       [-0.,  0., -0., ..., -0.,  0., -0.],
       [ 0., -0.,  0., ...,  0., -0.,  0.],
       ...,
       [ 0., -0.,  0., ...,  0., -0.,  0.],
       [-0.,  0., -0., ..., -0.,  0., -0.],
       [ 0., -0.,  0., ...,  0., -0.,  0.]])

## Check whether we can calculate the filling on a certain site.

In [12]:
# The dimension will be three by three since we have three sites.
diagonal_op = np.zeros((6,6))
diagonal_op[0,0] = 1
op_eval = basis.evaluateDiagonalOperator(diagonal_op, sparse_rep=False)

In [13]:
print(op_eval)

[[6. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]
 [0. 0. 5. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
GSParameters.calculateExpectationValue(op_eval).real

1.0000000000000013

The sum of the occupations should equal the total number of bosons in the system. We can check this.

In [15]:
sum_of_n = 0
for i in range(6):
    diagonal_op_2 = np.zeros((6,6))
    diagonal_op_2[i, i] = 1
    op_eval_2 = basis.evaluateDiagonalOperator(diagonal_op_2, sparse_rep=False)
    sum_of_n += GSParameters.calculateExpectationValue(op_eval_2).real

In [16]:
sum_of_n

6.000000000000007