In [1]:
import prototypes.BoseHubbardModel as bh
import numpy as np

## Testing basic functionalities of the code.

In [2]:
bh.AdjacencyMatrix(6).withPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [3]:
bh.AdjacencyMatrix(6).withoutPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

In [4]:
basis = bh.ONVBasis(3,3)

In [5]:
basis.ONVs

array([[3, 0, 0],
       [2, 1, 0],
       [2, 0, 1],
       [1, 2, 0],
       [1, 1, 1],
       [1, 0, 2],
       [0, 3, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 0, 3]])

In [6]:
# 3 sites, 3 bosons
# t=0.1, U=2
# w_ii = 0
# Periodic boundary conditions

H = bh.BoseHubbardHamiltonian(3, 3, 0.1, 2, [0]*3, True)

In [7]:
print(basis.evaluateHamiltonian(H))

  (0, 0)	6.0
  (0, 1)	0.17320508075688773
  (0, 2)	0.17320508075688773
  (1, 0)	0.17320508075688773
  (1, 1)	2.0
  (1, 2)	0.1
  (1, 3)	0.2
  (1, 4)	0.14142135623730953
  (2, 0)	0.17320508075688773
  (2, 1)	0.1
  (2, 2)	2.0
  (2, 4)	0.14142135623730953
  (2, 5)	0.2
  (3, 1)	0.2
  (3, 3)	2.0
  (3, 4)	0.14142135623730953
  (3, 6)	0.17320508075688773
  (3, 7)	0.1
  (4, 1)	0.14142135623730953
  (4, 2)	0.14142135623730953
  (4, 3)	0.14142135623730953
  (4, 5)	0.14142135623730953
  (4, 7)	0.14142135623730953
  (4, 8)	0.14142135623730953
  (5, 2)	0.2
  (5, 4)	0.14142135623730953
  (5, 5)	2.0
  (5, 8)	0.1
  (5, 9)	0.17320508075688773
  (6, 3)	0.17320508075688773
  (6, 6)	6.0
  (6, 7)	0.17320508075688773
  (7, 3)	0.1
  (7, 4)	0.14142135623730953
  (7, 6)	0.17320508075688773
  (7, 7)	2.0
  (7, 8)	0.2
  (8, 4)	0.14142135623730953
  (8, 5)	0.1
  (8, 7)	0.2
  (8, 8)	2.0
  (8, 9)	0.17320508075688773
  (9, 5)	0.17320508075688773
  (9, 8)	0.17320508075688773
  (9, 9)	6.0


## Solving the problem.

In [8]:
H_eval = basis.evaluateHamiltonian(H)
GSParameters = bh.BoseHubbardSolver(H_eval).groundState()

In [9]:
GSParameters.energy.real

-0.05125275715716526

In [10]:
GSParameters.C.real

array([ 0.00342048, -0.05975045, -0.05975045, -0.05975045,  0.98921393,
       -0.05975045,  0.00342048, -0.05975045, -0.05975045,  0.00342048])

In [11]:
np.set_printoptions(3, suppress=True)
GSParameters.singleParticleDensityMatrix().real

array([[ 0.   , -0.   , -0.   , -0.   ,  0.003, -0.   ,  0.   , -0.   ,
        -0.   ,  0.   ],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [ 0.003, -0.059, -0.059, -0.059,  0.979, -0.059,  0.003, -0.059,
        -0.059,  0.003],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [ 0.   , -0.   , -0.   , -0.   ,  0.003, -0.   ,  0.   , -0.   ,
        -0.   ,  0.   ],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [-0.   ,  0.004,  0.004,  0.004, -0.059,  0.004, -0.   ,  0.004,
         0.004, -0.   ],
       [ 0.   , -0.   , -0.   , -0.   ,  0.003, -0.   ,  0.   , -0.   ,
        -0.   ,  0.   ]])

## Check whether we can calculate the filling on a certain site.

In [12]:
# The dimension will be three by three since we have three sites.
diagonal_op = np.zeros((3,3))
diagonal_op[0,0] = 1
op_eval = basis.evaluateDiagonalOperator(diagonal_op, sparse_rep=False)

In [13]:
print(op_eval)

[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
GSParameters.calculateExpectationValue(op_eval).real

0.9999999999999998

The sum of the occupations should equal the total number of bosons in the system. We can check this.

In [15]:
sum_of_n = 0
for i in range(3):
    diagonal_op_2 = np.zeros((3,3))
    diagonal_op_2[i, i] = 1
    op_eval_2 = basis.evaluateDiagonalOperator(diagonal_op_2, sparse_rep=False)
    sum_of_n += GSParameters.calculateExpectationValue(op_eval_2).real

In [16]:
sum_of_n

2.999999999999999