In [1]:
import BoseHubbardModel as bh
import numpy as np

## Testing basic functionalities of the code.

In [2]:
bh.AdjacencyMatrix(6).withPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [3]:
bh.AdjacencyMatrix(6).withoutPeriodicBoundaryConditions()

array([[0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

In [4]:
basis = bh.ONVBasis(3,3)

In [5]:
basis.ONVs

array([[3, 0, 0],
       [2, 1, 0],
       [2, 0, 1],
       [1, 2, 0],
       [1, 1, 1],
       [1, 0, 2],
       [0, 3, 0],
       [0, 2, 1],
       [0, 1, 2],
       [0, 0, 3]])

In [6]:
# 3 sites, 3 bosons
# t=0.1, U=2
# w_ii = 0
# Periodic boundary conditions

H = bh.BoseHubbardHamiltonian(3, 3, 0.1, 2, [0]*3, True)

In [7]:
print(basis.evaluateHamiltonian(H))

  (0, 0)	6.0
  (0, 1)	0.17320508075688773
  (0, 2)	0.17320508075688773
  (1, 0)	0.17320508075688773
  (1, 1)	2.0
  (1, 2)	0.1
  (1, 3)	0.2
  (1, 4)	0.14142135623730953
  (2, 0)	0.17320508075688773
  (2, 1)	0.1
  (2, 2)	2.0
  (2, 4)	0.14142135623730953
  (2, 5)	0.2
  (3, 1)	0.2
  (3, 3)	2.0
  (3, 4)	0.14142135623730953
  (3, 6)	0.17320508075688773
  (3, 7)	0.1
  (4, 1)	0.14142135623730953
  (4, 2)	0.14142135623730953
  (4, 3)	0.14142135623730953
  (4, 5)	0.14142135623730953
  (4, 7)	0.14142135623730953
  (4, 8)	0.14142135623730953
  (5, 2)	0.2
  (5, 4)	0.14142135623730953
  (5, 5)	2.0
  (5, 8)	0.1
  (5, 9)	0.17320508075688773
  (6, 3)	0.17320508075688773
  (6, 6)	6.0
  (6, 7)	0.17320508075688773
  (7, 3)	0.1
  (7, 4)	0.14142135623730953
  (7, 6)	0.17320508075688773
  (7, 7)	2.0
  (7, 8)	0.2
  (8, 4)	0.14142135623730953
  (8, 5)	0.1
  (8, 7)	0.2
  (8, 8)	2.0
  (8, 9)	0.17320508075688773
  (9, 5)	0.17320508075688773
  (9, 8)	0.17320508075688773
  (9, 9)	6.0


## Solving the problem.

In [8]:
H_eval = basis.evaluateHamiltonian(H)
GSParameters = bh.BoseHubbardSolver(H_eval).groundState()

In [9]:
GSParameters.energy.real

2.1655578712636623

In [10]:
GSParameters.C.real

array([-5.86742750e-02, -4.05149936e-03, -1.02033236e-03, -3.00097021e-02,
        2.30935931e-14,  3.23561335e-02, -6.74618480e-01, -2.83046341e-02,
        3.10300345e-02,  7.33292755e-01])

In [11]:
np.set_printoptions(3, suppress=True)
GSParameters.singleParticleDensityMatrix().real

array([[ 0.003,  0.   ,  0.   ,  0.002, -0.   , -0.002,  0.04 ,  0.002,
        -0.002, -0.043],
       [ 0.   ,  0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.003,  0.   ,
        -0.   , -0.003],
       [ 0.   ,  0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.001,  0.   ,
        -0.   , -0.001],
       [ 0.002,  0.   ,  0.   ,  0.001, -0.   , -0.001,  0.02 ,  0.001,
        -0.001, -0.022],
       [-0.   , -0.   , -0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ,
         0.   ,  0.   ],
       [-0.002, -0.   , -0.   , -0.001,  0.   ,  0.001, -0.022, -0.001,
         0.001,  0.024],
       [ 0.04 ,  0.003,  0.001,  0.02 , -0.   , -0.022,  0.455,  0.019,
        -0.021, -0.495],
       [ 0.002,  0.   ,  0.   ,  0.001, -0.   , -0.001,  0.019,  0.001,
        -0.001, -0.021],
       [-0.002, -0.   , -0.   , -0.001,  0.   ,  0.001, -0.021, -0.001,
         0.001,  0.023],
       [-0.043, -0.003, -0.001, -0.022,  0.   ,  0.024, -0.495, -0.021,
         0.023,  0.538]])

## Check whether we can calculate the filling on a certain site.

In [15]:
# The dimension will be three by three since we have three sites.
diagonal_op = np.zeros((3,3))
diagonal_op[0,0] = 1
op_eval = basis.evaluateDiagonalOperator(diagonal_op, sparse_representation=False)

In [16]:
print(op_eval)

[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
GSParameters.calculateExpectationValue(op_eval).real

0.012310424693417843

The sum of the occupations should equal the total number of bosons in the system. We can check this.

In [19]:
sum_of_n = 0
for i in range(3):
    diagonal_op_2 = np.zeros((3,3))
    diagonal_op_2[i, i] = 1
    op_eval_2 = basis.evaluateDiagonalOperator(diagonal_op_2, sparse_representation=False)
    sum_of_n += GSParameters.calculateExpectationValue(op_eval_2).real

In [20]:
sum_of_n

3.000000000000001