In [1]:
import prototypes.BoseHubbardModel as bh
import numpy as np

In [2]:
basis = bh.ONVBasis(4,4,3)

In [3]:
basis.ONVs

array([[3, 1, 0, 0],
       [3, 0, 1, 0],
       [3, 0, 0, 1],
       [2, 2, 0, 0],
       [2, 1, 1, 0],
       [2, 1, 0, 1],
       [2, 0, 2, 0],
       [2, 0, 1, 1],
       [2, 0, 0, 2],
       [1, 3, 0, 0],
       [1, 2, 1, 0],
       [1, 2, 0, 1],
       [1, 1, 2, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 2],
       [1, 0, 3, 0],
       [1, 0, 2, 1],
       [1, 0, 1, 2],
       [1, 0, 0, 3],
       [0, 3, 1, 0],
       [0, 3, 0, 1],
       [0, 2, 2, 0],
       [0, 2, 1, 1],
       [0, 2, 0, 2],
       [0, 1, 3, 0],
       [0, 1, 2, 1],
       [0, 1, 1, 2],
       [0, 1, 0, 3],
       [0, 0, 3, 1],
       [0, 0, 2, 2],
       [0, 0, 1, 3]])

In [4]:
# 3 sites, 3 bosons
# t=0.1, U=2
# w_ii = 0
# Periodic boundary conditions

H = bh.BoseHubbardHamiltonian(4, 4, 0.1, 2, [0]*4, True)

In [5]:
print(basis.evaluateHamiltonian(H))

  (0, 0)	6.2449489742783175
  (0, 3)	0.2449489742783178
  (0, 4)	0.14142135623730953
  (0, 7)	0.17320508075688773
  (1, 0)	0.1
  (1, 1)	6.0
  (1, 4)	0.17320508075688773
  (1, 5)	0.1
  (1, 8)	0.2449489742783178
  (2, 0)	0.17320508075688773
  (2, 2)	6.0
  (2, 4)	0.1
  (2, 5)	0.17320508075688773
  (2, 11)	0.14142135623730953
  (3, 1)	0.17320508075688773
  (3, 3)	4.0
  (3, 6)	0.14142135623730953
  (3, 9)	0.2449489742783178
  (3, 13)	0.14142135623730953
  (4, 2)	0.17320508075688773
  (4, 3)	0.14142135623730953
  (4, 4)	2.0
  (4, 7)	0.24142135623730954
  (4, 10)	0.2
  (4, 14)	0.2
  :	:
  (25, 17)	0.1
  (25, 23)	0.14142135623730953
  (25, 25)	2.2
  (25, 27)	0.17320508075688773
  (25, 30)	0.1
  (26, 14)	0.17320508075688773
  (26, 18)	0.1
  (26, 25)	0.17320508075688773
  (26, 26)	2.1732050807568877
  (26, 29)	0.2449489742783178
  (27, 1)	0.1
  (27, 15)	0.1
  (27, 27)	6.0
  (27, 28)	0.2449489742783178
  (28, 16)	0.14142135623730953
  (28, 26)	0.14142135623730953
  (28, 28)	6.0
  (28, 29)	0.24494

## Solving the problem.

In [6]:
H_eval = basis.evaluateHamiltonian(H)
GSParameters = bh.BoseHubbardSolver(H_eval).groundState()

In [7]:
GSParameters.energy.real

0.07970906656816368

In [8]:
GSParameters.C.real

array([-2.89839321e-05,  2.87867162e-03, -6.30317923e-04,  7.62943056e-03,
        4.81136336e-03, -1.05961054e-01,  2.59802485e-03,  1.18683117e-02,
       -3.62997942e-02, -5.50784430e-04,  1.15291339e-02, -7.40076830e-02,
       -2.27304060e-03,  9.85467689e-01, -2.82259994e-03,  2.56215060e-05,
       -6.69854326e-02,  7.59591873e-03,  3.01626832e-03,  2.07915781e-03,
        9.18149074e-04, -3.61835029e-02,  9.49035648e-03,  2.46356075e-03,
        8.10850687e-04, -6.67023229e-02,  5.50885315e-03, -4.34066476e-05,
        1.46852601e-03, -3.34493300e-04, -3.79770812e-05])

In [9]:
np.set_printoptions(3, suppress=True)
GSParameters.singleParticleDensityMatrix().real

array([[ 0.   , -0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,
         0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   ,  0.   , -0.   ,
         0.   , -0.   , -0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,
        -0.   ,  0.   , -0.   ,  0.   , -0.   ,  0.   ,  0.   ],
       [-0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,
        -0.   , -0.   ,  0.   , -0.   , -0.   ,  0.003, -0.   ,  0.   ,
        -0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,
         0.   , -0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ],
       [ 0.   , -0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,
         0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.001,  0.   , -0.   ,
         0.   , -0.   , -0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,
        -0.   ,  0.   , -0.   ,  0.   , -0.   ,  0.   ,  0.   ],
       [-0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.001,  0.   ,  0.   ,
        -0.   , -0.   ,  0.   , -0.001, -0.   ,  0.008, -0.   ,  0.   ,
        -0.00

## Check whether we can calculate the filling on a certain site.

In [10]:
# The dimension will be three by three since we have three sites.
diagonal_op = np.zeros((4,4))
diagonal_op[0,0] = 1
op_eval = basis.evaluateDiagonalOperator(diagonal_op, sparse_rep=False)

In [11]:
print(op_eval)

[[3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 

In [12]:
GSParameters.calculateExpectationValue(op_eval).real

1.0068987293314848

The sum of the occupations should equal the total number of bosons in the system. We can check this.

In [13]:
sum_of_n = 0
for i in range(4):
    diagonal_op_2 = np.zeros((4,4))
    diagonal_op_2[i, i] = 1
    op_eval_2 = basis.evaluateDiagonalOperator(diagonal_op_2, sparse_rep=False)
    sum_of_n += GSParameters.calculateExpectationValue(op_eval_2).real

In [14]:
sum_of_n

4.000000000000001